name: Update freddit.net

on:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: make update
